
spring:
   datasource:
      url: jdbc:mysql://localhost:55005/board?useSSL=false&serverTimezone=Asia/Seoul
      username: root
      password: 1234
      initialize: false

   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
      properties:
         hibernate:
            format_sql: true
